development:
  clients:
    default:
      database: library_dev
      hosts:
        - mongo:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: library_test
      hosts:
        - mongo:27017
      options:
        server_selection_timeout: 1
